In [14]:
import numpy as np
import pandas as pd
import yfinance as yf
from pprint import pprint
from datetime import date
from dateutil.relativedelta import relativedelta

In [12]:
msft = yf.Ticker("MSFT")

In [13]:
pprint(msft.info)

{'52WeekChange': -0.08625555,
 'SandP52WeekChange': 0.27181315,
 'address1': 'One Microsoft Way',
 'allTimeHigh': 555.45,
 'allTimeLow': 0.088542,
 'ask': 418.97,
 'askSize': 2,
 'auditRisk': 9,
 'averageAnalystRating': '1.3 - Strong Buy',
 'averageDailyVolume10Day': 39745710,
 'averageDailyVolume3Month': 34617223,
 'averageVolume': 34617223,
 'averageVolume10days': 39745710,
 'beta': 1.103,
 'bid': 415.53,
 'bidSize': 3,
 'boardRisk': 8,
 'bookValue': 55.777,
 'city': 'Redmond',
 'companyOfficers': [{'age': 58,
                      'exercisedValue': 0,
                      'fiscalYear': 2025,
                      'maxAge': 1,
                      'name': 'Mr. Satya  Nadella',
                      'title': 'Chairman & CEO',
                      'totalPay': 12251294,
                      'unexercisedValue': 0,
                      'yearBorn': 1967},
                     {'age': 66,
                      'exercisedValue': 0,
                      'fiscalYear': 2025,
                      'maxAge': 1,
                      'name': 'Mr. Bradford L. Smith LCA',
                      'title': 'President & Vice Chairman',
                      'totalPay': 4532750,
                      'unexercisedValue': 0,
                      'yearBorn': 1959},
                     {'age': 53,
                      'exercisedValue': 0,
                      'fiscalYear': 2025,
                      'maxAge': 1,
                      'name': 'Ms. Amy E. Hood',
                      'title': 'Executive VP & CFO',
                      'totalPay': 4444191,
                      'unexercisedValue': 0,
                      'yearBorn': 1972},
                     {'age': 53,
                      'exercisedValue': 0,
                      'fiscalYear': 2025,
                      'maxAge': 1,
                      'name': 'Mr. Takeshi  Numoto',
                      'title': 'Executive VP & Chief Marketing Officer',
                      'totalPay': 2871250,
                      'unexercisedValue': 0,
                      'yearBorn': 1972},
                     {'age': 51,
                      'exercisedValue': 0,
                      'fiscalYear': 2025,
                      'maxAge': 1,
                      'name': 'Mr. Judson B. Althoff',
                      'title': 'Executive VP & CEO of Commercial Business',
                      'totalPay': 4490115,
                      'unexercisedValue': 0,
                      'yearBorn': 1974},
                     {'age': 53,
                      'exercisedValue': 0,
                      'fiscalYear': 2025,
                      'maxAge': 1,
                      'name': 'Ms. Carolina  Dybeck Happe',
                      'title': 'Executive VP & COO',
                      'unexercisedValue': 0,
                      'yearBorn': 1972},
                     {'age': 59,
                      'exercisedValue': 0,
                      'fiscalYear': 2025,
                      'maxAge': 1,
                      'name': 'Ms. Alice L. Jolla',
                      'title': 'Corporate VP & Chief Accounting Officer',
                      'unexercisedValue': 0,
                      'yearBorn': 1966},
                     {'exercisedValue': 0,
                      'fiscalYear': 2025,
                      'maxAge': 1,
                      'name': 'Mr. Matthew  Kerner',
                      'title': 'CTO & Corporate VP of Worldwide Sales and '
                               'Solutions',
                      'unexercisedValue': 0},
                     {'exercisedValue': 0,
                      'fiscalYear': 2025,
                      'maxAge': 1,
                      'name': 'Jonathan  Neilson',
                      'title': 'Vice President of Investor Relations',
                      'unexercisedValue': 0},
                     {'exercisedValue': 0,
                      'fiscalYear': 2025,
                      'maxAge': 1,
                      'name': 'Mr. Jonathan M. Palmer',
                      'title': 'Corporate Vice President & Chief Legal Officer',
                      'unexercisedValue': 0}],
 'compensationAsOfEpochDate': 1767139200,
 'compensationRisk': 5,
 'corporateActions': [],
 'country': 'United States',
 'cryptoTradeable': False,
 'currency': 'USD',
 'currentPrice': 416.67,
 'currentRatio': 1.283,
 'customPriceAlertConfidence': 'HIGH',
 'dateShortInterest': 1778803200,
 'dayHigh': 429.47,
 'dayLow': 414.4,
 'debtToEquity': 30.271,
 'displayName': 'Microsoft',
 'dividendDate': 1781136000,
 'dividendRate': 3.64,
 'dividendYield': 0.87,
 'earningsCallTimestampEnd': 1777498200,
 'earningsCallTimestampStart': 1777498200,
 'earningsGrowth': 0.234,
 'earningsQuarterlyGrowth': 0.231,
 'earningsTimestamp': 1777492800,
 'earningsTimestampEnd': 1785355200,
 'earningsTimestampStart': 1785355200,
 'ebitda': 184457003008,
 'ebitdaMargins': 0.57956004,
 'enterpriseToEbitda': 17.036,
 'enterpriseToRevenue': 9.873,
 'enterpriseValue': 3142409781248,
 'epsCurrentYear': 16.82726,
 'epsForward': 19.34941,
 'epsTrailingTwelveMonths': 16.79,
 'esgPopulated': False,
 'exDividendDate': 1779321600,
 'exchange': 'NMS',
 'exchangeDataDelayedBy': 0,
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'executiveTeam': [],
 'fiftyDayAverage': 406.3312,
 'fiftyDayAverageChange': 10.338806,
 'fiftyDayAverageChangePercent': 0.025444282,
 'fiftyTwoWeekChangePercent': -8.625555,
 'fiftyTwoWeekHigh': 555.45,
 'fiftyTwoWeekHighChange': -138.78,
 'fiftyTwoWeekHighChangePercent': -0.24985147,
 'fiftyTwoWeekLow': 356.28,
 'fiftyTwoWeekLowChange': 60.390015,
 'fiftyTwoWeekLowChangePercent': 0.16950156,
 'fiftyTwoWeekRange': '356.28 - 555.45',
 'financialCurrency': 'USD',
 'firstTradeDateMilliseconds': 511108200000,
 'fiveYearAvgDividendYield': 0.79,
 'floatShares': 7417514905,
 'forwardEps': 19.34941,
 'forwardPE': 21.53399,
 'freeCashflow': 37011251200,
 'fullExchangeName': 'NasdaqGS',
 'fullTimeEmployees': 228000,
 'gmtOffSetMilliseconds': -14400000,
 'governanceEpochDate': 1780531200,
 'grossMargins': 0.68309,
 'grossProfits': 217409994752,
 'hasPrePostMarketData': True,
 'heldPercentInsiders': 0.0008,
 'heldPercentInstitutions': 0.75767,
 'impliedSharesOutstanding': 7428434704,
 'industry': 'Software - Infrastructure',
 'industryDisp': 'Software - Infrastructure',
 'industryKey': 'software-infrastructure',
 'irWebsite': 'http://www.microsoft.com/investor/default.aspx',
 'isEarningsDateEstimate': True,
 'language': 'en-US',
 'lastDividendDate': 1779321600,
 'lastDividendValue': 0.91,
 'lastFiscalYearEnd': 1751241600,
 'lastSplitDate': 1045526400,
 'lastSplitFactor': '2:1',
 'longBusinessSummary': 'Microsoft Corporation develops and supports software, '
                        'services, devices, and solutions worldwide. The '
                        'Productivity and Business Processes segment offers '
                        'Microsoft 365 commercial, enterprise mobility + '
                        'security, windows commercial, power BI, exchange, '
                        'sharepoint, Microsoft teams, security and compliance, '
                        'and copilot; Microsoft 365 commercial products, such '
                        'as Windows commercial on-premises and office licensed '
                        'services; Microsoft 365 consumer products and cloud '
                        'services, including Microsoft 365 consumer '
                        'subscriptions, office licensed on-premises, and other '
                        'consumer services; LinkedIn; dynamics products and '
                        'cloud services, such as dynamics 365, cloud-based '
                        'applications, and on-premises ERP and CRM '
                        'applications. Its Intelligent Cloud segment provides '
                        'Server products and cloud services comprising Azure '
                        'and other cloud services, GitHub, Nuance Healthcare, '
                        'virtual desktop offerings, and other cloud services; '
                        'server products, including SQL and windows server, '
                        'visual studio and system center related client access '
                        'licenses, and other on-premises offerings; enterprise '
                        'and partner services, such as enterprise support and '
                        'nuance professional services, industry solutions, '
                        'Microsoft partner network, and learning experience. '
                        'The Personal Computing segment provides windows and '
                        'devices, such as Windows OEM licensing and devices '
                        'and surface and PC accessories; gaming services and '
                        'solutions, such as Xbox hardware, content, and '
                        'services, first- and third-party content Xbox game '
                        'pass, subscriptions, and cloud gaming, advertising, '
                        'and other cloud services; search and news advertising '
                        'services that includes Bing and Copilot, Microsoft '
                        'News and Edge, and third-party affiliates. It sells '
                        'its products through OEMs, distributors, and '
                        'resellers; and online and retail stores. The company '
                        'has a strategic collaboration with Mayo Clinic, Inc. '
                        'for the development of a frontier AI model for '
                        'healthcare. The company was founded in 1975 and is '
                        'headquartered in Redmond, Washington.',
 'longName': 'Microsoft Corporation',
 'market': 'us_market',
 'marketCap': 3095206035456,
 'marketState': 'PREPRE',
 'maxAge': 86400,
 'messageBoardId': 'finmb_21835',
 'mostRecentQuarter': 1774915200,
 'netIncomeToCommon': 125215997952,
 'nextFiscalYearEnd': 1782777600,
 'nonDilutedMarketCap': 3095205888115,
 'numberOfAnalystOpinions': 55,
 'open': 428.34,
 'operatingCashflow': 170141007872,
 'operatingMargins': 0.46326,
 'overallRisk': 5,
 'payoutRatio': 0.20729999,
 'pegRatio': 1.28,
 'phone': '425 882 8080',
 'postMarketChange': -4.2700195,
 'postMarketChangePercent': -1.0247965,
 'postMarketPrice': 412.4,
 'postMarketTime': 1780703999,
 'previousClose': 428.05002,
 'priceEpsCurrentYear': 24.76161,
 'priceHint': 2,
 'priceToBook': 7.4702835,
 'priceToSalesTrailing12Months': 9.725003,
 'profitMargins': 0.39341998,
 'quickRatio': 1.142,
 'quoteSourceName': 'Nasdaq Real Time Price',
 'quoteType': 'EQUITY',
 'recommendationKey': 'strong_buy',
 'recommendationMean': 1.33929,
 'region': 'US',
 'regularMarketChange': -11.380005,
 'regularMarketChangePercent': -2.6585689,
 'regularMarketDayHigh': 429.47,
 'regularMarketDayLow': 414.4,
 'regularMarketDayRange': '414.4 - 429.47',
 'regularMarketOpen': 428.34,
 'regularMarketPreviousClose': 428.05002,
 'regularMarketPrice': 416.67,
 'regularMarketTime': 1780689601,
 'regularMarketVolume': 34782164,
 'returnOnAssets': 0.14814,
 'returnOnEquity': 0.34013999,
 'revenueGrowth': 0.183,
 'revenuePerShare': 42.836,
 'sector': 'Technology',
 'sectorDisp': 'Technology',
 'sectorKey': 'technology',
 'shareHolderRightsRisk': 2,
 'sharesOutstanding': 7428434704,
 'sharesPercentSharesOut': 0.0104,
 'sharesShort': 77302679,
 'sharesShortPreviousMonthDate': 1776211200,
 'sharesShortPriorMonth': 83407242,
 'shortName': 'Microsoft Corporation',
 'shortPercentOfFloat': 0.0104,
 'shortRatio': 2.15,
 'sourceInterval': 15,
 'state': 'WA',
 'symbol': 'MSFT',
 'targetHighPrice': 870.0,
 'targetLowPrice': 400.0,
 'targetMeanPrice': 560.946,
 'targetMedianPrice': 555.0,
 'totalCash': 78227996672,
 'totalCashPerShare': 10.531,
 'totalDebt': 125431996416,
 'totalRevenue': 318272995328,
 'tradeable': False,
 'trailingAnnualDividendRate': 3.56,
 'trailingAnnualDividendYield': 0.008316785,
 'trailingEps': 16.79,
 'trailingPE': 24.816557,
 'trailingPegRatio': 1.2845,
 'triggerable': True,
 'twoHundredDayAverage': 457.29114,
 'twoHundredDayAverageChange': -40.621124,
 'twoHundredDayAverageChangePercent': -0.0888299,
 'typeDisp': 'Equity',
 'volume': 34782164,
 'website': 'https://www.microsoft.com',
 'zip': '98052-6399'}

In [4]:
msft_1y = msft.history(period="1y")

In [5]:
msft_1y.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-06-06 00:00:00-04:00,466.364877,469.589124,465.065261,466.652588,15285600,0.0,0.0
2025-06-09 00:00:00-04:00,465.977996,469.678419,464.906537,469.003815,16469900,0.0,0.0
2025-06-10 00:00:00-04:00,467.456143,469.053370,463.259652,467.188293,15375900,0.0,0.0
2025-06-11 00:00:00-04:00,466.295444,471.702269,465.938312,468.874847,16399200,0.0,0.0
2025-06-12 00:00:00-04:00,471.255789,476.613022,469.767676,475.075287,18950600,0.0,0.0

In [6]:
msft_1y.shape

(251, 7)

In [7]:
msft_1mo = msft.history(period="1mo")

In [8]:
msft_1mo.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-05-06 00:00:00-04:00,407.118227,417.515721,404.234459,413.065338,30285900,0.0,0.0
2026-05-07 00:00:00-04:00,419.202049,427.055066,417.854991,419.860626,34942400,0.0,0.0
2026-05-08 00:00:00-04:00,416.487953,417.725263,413.105265,414.222839,33383800,0.0,0.0
2026-05-11 00:00:00-04:00,406.988502,411.798092,404.623629,411.768158,35657900,0.0,0.0
2026-05-12 00:00:00-04:00,413.584222,414.602007,405.761170,406.888702,38594200,0.0,0.0

In [9]:
msft_1mo.shape

(22, 7)

Watchlist dataset
- Given watchlist (list of tickers), show daily stocks prices for last 5 years
- Columns: Date, Open, High, Low, Close, Volume, Ticker
- Scrape watchlist from Google Finance?

In [31]:
watchlist_cad = [
    'bns', 'cls', 'xgd', 'svr', 'mfc', 'sppp', 'slf', 'tsat', 
    'tvk', 'tfii', 'wsp'
]

watchlist_cad = [x + ".to" for x in watchlist_cad]

watchlist_usd = [
    'baba', 'googl', 'aapl', 'azo', 'bah', 'csco', 'crwv', 
    'dell', 'docs', 'itot', 'mod', 'orcl', 'pltr', 'voo',
    'wm', 'wsm'
]

In [41]:
start_dt = date.today() - relativedelta(years=5)
print(start_dt)

2021-06-08

In [42]:
finance_df = yf.download(watchlist_cad, start=start_dt)

[*********************100%***********************]  11 of 11 completed

In [43]:
# finance_df.columns = ['_'.join(col) for col in finance_df.columns]
# finance_df.columns = [col.replace(" ", "_").replace(".", "_") for col in finance_df.columns]

In [44]:
finance_df.head()

Price           Close                                                 \
Ticker         BNS.TO CLS.TO     MFC.TO     SLF.TO    SPPP.TO SVR.TO
2021-06-08  61.313793  10.33  19.821030  52.451160  23.950001  14.15
2021-06-09  61.162727  10.25  19.679344  52.200466  23.950001  14.13
2021-06-10  61.056992  10.22  19.395962  51.731430  23.700001  14.34
2021-06-11  61.155178  10.09  19.474678  51.885082  23.760000  14.32
2021-06-14  61.064529   9.90  19.356602  51.367523  23.660000  14.22

Price                                                  ...  Volume            \
Ticker         TFII.TO TSAT.TO     TVK.TO      WSP.TO  ...  CLS.TO    MFC.TO
2021-06-08  105.469032     NaN  16.795803  130.687729  ...   66800   7451700
2021-06-09  104.609085     NaN  16.739285  131.322205  ...  128700   3698000
2021-06-10  104.964272     NaN  16.908844  132.898849  ...   74000   6892800
2021-06-11  105.627930     NaN  16.918264  133.437241  ...   86800   5017000
2021-06-14  106.553246     NaN  16.918264  135.350327  ...  231300  12929400

Price
Ticker       SLF.TO SPPP.TO SVR.TO TFII.TO TSAT.TO TVK.TO  WSP.TO   XGD.TO
2021-06-08  1314700    1000   7200  329200     NaN    500  148700   264700
2021-06-09  1650700       0  23300  299600     NaN   3200  128600   208700
2021-06-10  1281000    1000  10100  215400     NaN  16800   93900  1128000
2021-06-11   600500     600  10300  178400     NaN   2800   84300   437800
2021-06-14  3072400     300   5700  139900     NaN      0  113500   329200

[5 rows x 55 columns]

In [45]:
finance_df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 1254 entries, 2021-06-08 to 2026-06-05
Data columns (total 55 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   (Close, BNS.TO)    1254 non-null   float64
 1   (Close, CLS.TO)    1254 non-null   float64
 2   (Close, MFC.TO)    1254 non-null   float64
 3   (Close, SLF.TO)    1254 non-null   float64
 4   (Close, SPPP.TO)   1254 non-null   float64
 5   (Close, SVR.TO)    1254 non-null   float64
 6   (Close, TFII.TO)   1254 non-null   float64
 7   (Close, TSAT.TO)   1135 non-null   float64
 8   (Close, TVK.TO)    1254 non-null   float64
 9   (Close, WSP.TO)    1254 non-null   float64
 10  (Close, XGD.TO)    1254 non-null   float64
 11  (High, BNS.TO)     1254 non-null   float64
 12  (High, CLS.TO)     1254 non-null   float64
 13  (High, MFC.TO)     1254 non-null   float64
 14  (High, SLF.TO)     1254 non-null   float64
 15  (High, SPPP.TO)    1254 non-null   float64
 16  (High, SVR.TO)     1254 non-null   float64
 17  (High, TFII.TO)    1254 non-null   float64
 18  (High, TSAT.TO)    1135 non-null   float64
 19  (High, TVK.TO)     1254 non-null   float64
 20  (High, WSP.TO)     1254 non-null   float64
 21  (High, XGD.TO)     1254 non-null   float64
 22  (Low, BNS.TO)      1254 non-null   float64
 23  (Low, CLS.TO)      1254 non-null   float64
 24  (Low, MFC.TO)      1254 non-null   float64
 25  (Low, SLF.TO)      1254 non-null   float64
 26  (Low, SPPP.TO)     1254 non-null   float64
 27  (Low, SVR.TO)      1254 non-null   float64
 28  (Low, TFII.TO)     1254 non-null   float64
 29  (Low, TSAT.TO)     1135 non-null   float64
 30  (Low, TVK.TO)      1254 non-null   float64
 31  (Low, WSP.TO)      1254 non-null   float64
 32  (Low, XGD.TO)      1254 non-null   float64
 33  (Open, BNS.TO)     1254 non-null   float64
 34  (Open, CLS.TO)     1254 non-null   float64
 35  (Open, MFC.TO)     1254 non-null   float64
 36  (Open, SLF.TO)     1254 non-null   float64
 37  (Open, SPPP.TO)    1254 non-null   float64
 38  (Open, SVR.TO)     1254 non-null   float64
 39  (Open, TFII.TO)    1254 non-null   float64
 40  (Open, TSAT.TO)    1135 non-null   float64
 41  (Open, TVK.TO)     1254 non-null   float64
 42  (Open, WSP.TO)     1254 non-null   float64
 43  (Open, XGD.TO)     1254 non-null   float64
 44  (Volume, BNS.TO)   1254 non-null   int64
 45  (Volume, CLS.TO)   1254 non-null   int64
 46  (Volume, MFC.TO)   1254 non-null   int64
 47  (Volume, SLF.TO)   1254 non-null   int64
 48  (Volume, SPPP.TO)  1254 non-null   int64
 49  (Volume, SVR.TO)   1254 non-null   int64
 50  (Volume, TFII.TO)  1254 non-null   int64
 51  (Volume, TSAT.TO)  1135 non-null   float64
 52  (Volume, TVK.TO)   1254 non-null   int64
 53  (Volume, WSP.TO)   1254 non-null   int64
 54  (Volume, XGD.TO)   1254 non-null   int64
dtypes: float64(45), int64(10)
memory usage: 548.6 KB