In [1]:
import numpy as np
import pandas as pd
import yfinance as yf

In [2]:
msft = yf.Ticker("MSFT")

In [7]:
print(msft.info)

{'address1': 'One Microsoft Way', 'city': 'Redmond', 'state': 'WA', 'zip': '98052-6399', 'country': 'United States', 'phone': '425 882 8080', 'website': 'https://www.microsoft.com', 'industry': 'Software - Infrastructure', 'industryKey': 'software-infrastructure', 'industryDisp': 'Software - Infrastructure', 'sector': 'Technology', 'sectorKey': 'technology', 'sectorDisp': 'Technology', 'longBusinessSummary': 'Microsoft Corporation develops and supports software, services, devices, and solutions worldwide. The Productivity and Business Processes segment offers Microsoft 365 commercial, enterprise mobility + security, windows commercial, power BI, exchange, sharepoint, Microsoft teams, security and compliance, and copilot; Microsoft 365 commercial products, such as Windows commercial on-premises and office licensed services; Microsoft 365 consumer products and cloud services, including Microsoft 365 consumer subscriptions, office licensed on-premises, and other consumer services; LinkedIn; dynamics products and cloud services, such as dynamics 365, cloud-based applications, and on-premises ERP and CRM applications. Its Intelligent Cloud segment provides Server products and cloud services comprising Azure and other cloud services, GitHub, Nuance Healthcare, virtual desktop offerings, and other cloud services; server products, including SQL and windows server, visual studio and system center related client access licenses, and other on-premises offerings; enterprise and partner services, such as enterprise support and nuance professional services, industry solutions, Microsoft partner network, and learning experience. The Personal Computing segment provides windows and devices, such as Windows OEM licensing and devices and surface and PC accessories; gaming services and solutions, such as Xbox hardware, content, and services, first- and third-party content Xbox game pass, subscriptions, and cloud gaming, advertising, and other cloud services; search and news advertising services that includes Bing and Copilot, Microsoft News and Edge, and third-party affiliates. It sells its products through OEMs, distributors, and resellers; and online and retail stores. The company has a strategic collaboration with Mayo Clinic, Inc. for the development of a frontier AI model for healthcare. The company was founded in 1975 and is headquartered in Redmond, Washington.', 'fullTimeEmployees': 228000, 'companyOfficers': [{'maxAge': 1, 'name': 'Mr. Satya  Nadella', 'age': 58, 'title': 'Chairman & CEO', 'yearBorn': 1967, 'fiscalYear': 2025, 'totalPay': 12251294, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Bradford L. Smith LCA', 'age': 66, 'title': 'President & Vice Chairman', 'yearBorn': 1959, 'fiscalYear': 2025, 'totalPay': 4532750, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Amy E. Hood', 'age': 53, 'title': 'Executive VP & CFO', 'yearBorn': 1972, 'fiscalYear': 2025, 'totalPay': 4444191, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Takeshi  Numoto', 'age': 53, 'title': 'Executive VP & Chief Marketing Officer', 'yearBorn': 1972, 'fiscalYear': 2025, 'totalPay': 2871250, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Judson B. Althoff', 'age': 51, 'title': 'Executive VP & CEO of Commercial Business', 'yearBorn': 1974, 'fiscalYear': 2025, 'totalPay': 4490115, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Carolina  Dybeck Happe', 'age': 53, 'title': 'Executive VP & COO', 'yearBorn': 1972, 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Alice L. Jolla', 'age': 59, 'title': 'Corporate VP & Chief Accounting Officer', 'yearBorn': 1966, 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Matthew  Kerner', 'title': 'CTO & Corporate VP of Worldwide Sales and Solutions', 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Jonathan  Neilson', 'title': 'Vice President of Investor Relations', 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Jonathan M. Palmer', 'title': 'Corporate Vice President & Chief Legal Officer', 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}], 'auditRisk': 9, 'boardRisk': 8, 'compensationRisk': 5, 'shareHolderRightsRisk': 2, 'overallRisk': 5, 'governanceEpochDate': 1780531200, 'compensationAsOfEpochDate': 1767139200, 'irWebsite': 'http://www.microsoft.com/investor/default.aspx', 'executiveTeam': [], 'maxAge': 86400, 'priceHint': 2, 'previousClose': 428.05, 'open': 428.34, 'dayLow': 414.4, 'dayHigh': 429.47, 'regularMarketPreviousClose': 428.05, 'regularMarketOpen': 428.34, 'regularMarketDayLow': 414.4, 'regularMarketDayHigh': 429.47, 'dividendRate': 3.64, 'dividendYield': 0.87, 'exDividendDate': 1779321600, 'payoutRatio': 0.20729999, 'fiveYearAvgDividendYield': 0.79, 'beta': 1.103, 'trailingPE': 24.831347, 'forwardPE': 21.53399, 'volume': 34383798, 'regularMarketVolume': 34383798, 'averageVolume': 34617223, 'averageVolume10days': 39745710, 'averageDailyVolume10Day': 39745710, 'bid': 415.53, 'ask': 418.97, 'bidSize': 3, 'askSize': 2, 'marketCap': 3095206035456, 'nonDilutedMarketCap': 3095205888115, 'fiftyTwoWeekLow': 356.28, 'fiftyTwoWeekHigh': 555.45, 'allTimeHigh': 555.45, 'allTimeLow': 0.088542, 'priceToSalesTrailing12Months': 9.725003, 'fiftyDayAverage': 406.3312, 'twoHundredDayAverage': 457.29114, 'trailingAnnualDividendRate': 3.56, 'trailingAnnualDividendYield': 0.008316785, 'currency': 'USD', 'tradeable': False, 'enterpriseValue': 3142409781248, 'profitMargins': 0.39341998, 'floatShares': 7417514905, 'sharesOutstanding': 7428434704, 'sharesShort': 77302679, 'sharesShortPriorMonth': 83407242, 'sharesShortPreviousMonthDate': 1776211200, 'dateShortInterest': 1778803200, 'sharesPercentSharesOut': 0.0104, 'heldPercentInsiders': 0.0008, 'heldPercentInstitutions': 0.75767, 'shortRatio': 2.15, 'shortPercentOfFloat': 0.0104, 'impliedSharesOutstanding': 7428434704, 'bookValue': 55.777, 'priceToBook': 7.4702835, 'lastFiscalYearEnd': 1751241600, 'nextFiscalYearEnd': 1782777600, 'mostRecentQuarter': 1774915200, 'earningsQuarterlyGrowth': 0.231, 'netIncomeToCommon': 125215997952, 'trailingEps': 16.78, 'forwardEps': 19.34941, 'pegRatio': 1.28, 'lastSplitFactor': '2:1', 'lastSplitDate': 1045526400, 'enterpriseToRevenue': 9.873, 'enterpriseToEbitda': 17.036, '52WeekChange': -0.08625555, 'SandP52WeekChange': 0.27181315, 'lastDividendValue': 0.91, 'lastDividendDate': 1779321600, 'quoteType': 'EQUITY', 'currentPrice': 416.67, 'targetHighPrice': 870.0, 'targetLowPrice': 400.0, 'targetMeanPrice': 560.946, 'targetMedianPrice': 555.0, 'recommendationMean': 1.33929, 'recommendationKey': 'strong_buy', 'numberOfAnalystOpinions': 55, 'totalCash': 78227996672, 'totalCashPerShare': 10.531, 'ebitda': 184457003008, 'totalDebt': 125431996416, 'quickRatio': 1.142, 'currentRatio': 1.283, 'totalRevenue': 318272995328, 'debtToEquity': 30.271, 'revenuePerShare': 42.836, 'returnOnAssets': 0.14814, 'returnOnEquity': 0.34013999, 'grossProfits': 217409994752, 'freeCashflow': 37011251200, 'operatingCashflow': 170141007872, 'earningsGrowth': 0.234, 'revenueGrowth': 0.183, 'grossMargins': 0.68309, 'ebitdaMargins': 0.57956004, 'operatingMargins': 0.46326, 'financialCurrency': 'USD', 'symbol': 'MSFT', 'language': 'en-US', 'region': 'US', 'typeDisp': 'Equity', 'quoteSourceName': 'Nasdaq Real Time Price', 'triggerable': True, 'customPriceAlertConfidence': 'HIGH', 'marketState': 'POSTPOST', 'exchange': 'NMS', 'messageBoardId': 'finmb_21835', 'exchangeTimezoneName': 'America/New_York', 'exchangeTimezoneShortName': 'EDT', 'gmtOffSetMilliseconds': -14400000, 'market': 'us_market', 'esgPopulated': False, 'hasPrePostMarketData': True, 'firstTradeDateMilliseconds': 511108200000, 'postMarketChangePercent': -1.0247965, 'postMarketPrice': 412.4, 'postMarketChange': -4.2700195, 'regularMarketChange': -11.38, 'regularMarketDayRange': '414.4 - 429.47', 'fullExchangeName': 'NasdaqGS', 'averageDailyVolume3Month': 34617223, 'fiftyTwoWeekLowChange': 60.390015, 'fiftyTwoWeekLowChangePercent': 0.16950156, 'fiftyTwoWeekRange': '356.28 - 555.45', 'fiftyTwoWeekHighChange': -138.78, 'fiftyTwoWeekHighChangePercent': -0.24985147, 'fiftyTwoWeekChangePercent': -8.625555, 'dividendDate': 1781136000, 'earningsTimestamp': 1777492800, 'earningsTimestampStart': 1785355200, 'earningsTimestampEnd': 1785355200, 'earningsCallTimestampStart': 1777498200, 'earningsCallTimestampEnd': 1777498200, 'isEarningsDateEstimate': True, 'epsTrailingTwelveMonths': 16.78, 'epsForward': 19.34941, 'epsCurrentYear': 16.82726, 'priceEpsCurrentYear': 24.76161, 'fiftyDayAverageChange': 10.338806, 'fiftyDayAverageChangePercent': 0.025444282, 'twoHundredDayAverageChange': -40.621124, 'twoHundredDayAverageChangePercent': -0.0888299, 'sourceInterval': 15, 'exchangeDataDelayedBy': 0, 'averageAnalystRating': '1.3 - Strong Buy', 'cryptoTradeable': False, 'regularMarketChangePercent': -2.65856, 'regularMarketPrice': 416.67, 'shortName': 'Microsoft Corporation', 'longName': 'Microsoft Corporation', 'corporateActions': [], 'postMarketTime': 1780703999, 'regularMarketTime': 1780689601, 'displayName': 'Microsoft', 'trailingPegRatio': 1.2845}

In [9]:
msft_1y = msft.history(period="1y")

In [10]:
msft_1y.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-06-06 00:00:00-04:00,466.364847,469.589093,465.065230,466.652557,15285600,0.0,0.0
2025-06-09 00:00:00-04:00,465.978026,469.678450,464.906567,469.003845,16469900,0.0,0.0
2025-06-10 00:00:00-04:00,467.456143,469.053370,463.259652,467.188293,15375900,0.0,0.0
2025-06-11 00:00:00-04:00,466.295444,471.702269,465.938312,468.874847,16399200,0.0,0.0
2025-06-12 00:00:00-04:00,471.255789,476.613022,469.767676,475.075287,18950600,0.0,0.0

In [11]:
msft_1y.shape

(251, 7)

In [12]:
msft_1mo = msft.history(period="1mo")

In [13]:
msft_1mo.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-05-06 00:00:00-04:00,407.118227,417.515721,404.234459,413.065338,30285900,0.0,0.0
2026-05-07 00:00:00-04:00,419.202049,427.055066,417.854991,419.860626,34942400,0.0,0.0
2026-05-08 00:00:00-04:00,416.487953,417.725263,413.105265,414.222839,33383800,0.0,0.0
2026-05-11 00:00:00-04:00,406.988502,411.798092,404.623629,411.768158,35657900,0.0,0.0
2026-05-12 00:00:00-04:00,413.584222,414.602007,405.761170,406.888702,38594200,0.0,0.0

In [14]:
msft_1mo.shape

(22, 7)

Watchlist dataset
- Given watchlist (list of tickers), show daily stocks prices for last 5 years
- Columns: Date, Open, High, Low, Close, Volume, Ticker
- Scrape watchlist from Google Finance?