In [5]:
import pandas as pd
import arff
from sqlalchemy import create_engine, inspect
from pathlib import Path
import patoolib
import os
from dotenv import load_dotenv

In [6]:
load_dotenv()

True

In [7]:
def get_database_uri():
    """
    Build a PostgreSQL connection URI from environment variables.

    Reads DB_USER, DB_PASSWORD, DB_HOST, DB_PORT, and DB_NAME from the
    environment (typically loaded from a .env file via python-dotenv) and
    returns a SQLAlchemy-compatible connection string.

    Returns:
        str: Connection URI in the format
             postgresql+psycopg2://user:password@host:port/dbname

    Raises:
        KeyError: If any required environment variable is not set.
    """
    
    db_user = os.getenv("DB_USER")
    db_password = os.getenv("DB_PASSWORD")
    db_host = os.getenv("DB_HOST")
    db_port = os.getenv("DB_PORT")
    db_name = os.getenv("DB_NAME")

    db_uri = f"postgresql+psycopg2://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}"

    return db_uri

In [8]:
db_uri = get_database_uri()
engine = create_engine(db_uri)

In [9]:
insp = inspect(engine)
tables = insp.get_table_names()
print(tables)

['glass_identification', 'bloodstain_patterns_gunshot_raw', 'bloodstain_patterns_impact_raw', 'phishing_email', 'phishing_url', 'phishing_website', 'iot_botnet.danmini_doorbell_benign_traffic', 'iot_botnet.ecobee_thermostat_benign_traffic', 'iot_botnet.ennio_doorbell_benign_traffic', 'iot_botnet.philips_b120n10_baby_benign_traffic', 'iot_botnet.provision_pt_737e_benign_traffic', 'iot_botnet.provision_pt_838_benign_traffic', 'iot_botnet.samsung_snh_1011_benign_traffic', 'iot_botnet.simplehome_xcs7_1002_benign_traffic', 'iot_botnet.simplehome_xcs7_1003_benign_traffic', 'iot_botnet.danmini_doorbell_gafgyt_combo', 'iot_botnet.danmini_doorbell_gafgyt_junk', 'iot_botnet.danmini_doorbell_gafgyt_scan', 'iot_botnet.danmini_doorbell_gafgyt_tcp', 'iot_botnet.danmini_doorbell_gafgyt_udp', 'iot_botnet.danmini_doorbell_mirai_ack', 'iot_botnet.danmini_doorbell_mirai_scan', 'iot_botnet.danmini_doorbell_mirai_syn', 'iot_botnet.danmini_doorbell_mirai_udp', 'iot_botnet.danmini_doorbell_mirai_udpplain', 'iot_botnet.ecobee_thermostat_gafgyt_combo', 'iot_botnet.ecobee_thermostat_gafgyt_junk', 'iot_botnet.ecobee_thermostat_gafgyt_scan', 'iot_botnet.ecobee_thermostat_gafgyt_tcp', 'iot_botnet.ecobee_thermostat_gafgyt_udp', 'credit_card_fraud', 'credit_card_client_default', 'iot_botnet.ecobee_thermostat_mirai_ack', 'iot_botnet.ecobee_thermostat_mirai_scan', 'iot_botnet.ecobee_thermostat_mirai_syn', 'iot_botnet.ecobee_thermostat_mirai_udp', 'iot_botnet.ecobee_thermostat_mirai_udpplain', 'iot_botnet.ennio_doorbell_gafgyt_combo', 'iot_botnet.ennio_doorbell_gafgyt_junk', 'iot_botnet.ennio_doorbell_gafgyt_scan', 'iot_botnet.ennio_doorbell_gafgyt_tcp', 'iot_botnet.ennio_doorbell_gafgyt_udp', 'iot_botnet.philips_b120n10_baby_gafgyt_combo', 'iot_botnet.philips_b120n10_baby_gafgyt_junk', 'iot_botnet.philips_b120n10_baby_gafgyt_scan', 'iot_botnet.philips_b120n10_baby_gafgyt_tcp', 'iot_botnet.philips_b120n10_baby_gafgyt_udp', 'iot_botnet.philips_b120n10_baby_mirai_ack', 'iot_botnet.philips_b120n10_baby_mirai_scan', 'iot_botnet.philips_b120n10_baby_mirai_syn', 'iot_botnet.philips_b120n10_baby_mirai_udp', 'iot_botnet.philips_b120n10_baby_mirai_udpplain', 'iot_botnet.provision_pt_737e_gafgyt_combo', 'iot_botnet.provision_pt_737e_gafgyt_junk', 'phishing_url_phiusiil', 'company_bankruptcy_taiwan', 'iot_botnet.provision_pt_737e_gafgyt_scan', 'iot_botnet.provision_pt_737e_gafgyt_tcp', 'iot_botnet.provision_pt_737e_gafgyt_udp', 'iot_botnet.provision_pt_737e_mirai_ack', 'iot_botnet.provision_pt_737e_mirai_scan', 'iot_botnet.provision_pt_737e_mirai_syn', 'iot_botnet.provision_pt_737e_mirai_udp', 'iot_botnet.provision_pt_737e_mirai_udpplain', 'iot_botnet.provision_pt_838_gafgyt_combo', 'iot_botnet.provision_pt_838_gafgyt_junk', 'iot_botnet.provision_pt_838_gafgyt_scan', 'iot_botnet.provision_pt_838_gafgyt_tcp', 'iot_botnet.provision_pt_838_gafgyt_udp', 'iot_botnet.provision_pt_838_mirai_ack', 'iot_botnet.provision_pt_838_mirai_scan', 'iot_botnet.provision_pt_838_mirai_syn', 'iot_botnet.provision_pt_838_mirai_udp', 'iot_botnet.provision_pt_838_mirai_udpplain', 'iot_botnet.samsung_snh_1011_gafgyt_combo', 'iot_botnet.samsung_snh_1011_gafgyt_junk', 'iot_botnet.samsung_snh_1011_gafgyt_scan', 'iot_botnet.samsung_snh_1011_gafgyt_tcp', 'iot_botnet.samsung_snh_1011_gafgyt_udp', 'iot_botnet.simplehome_xcs7_1002_gafgyt_combo', 'iot_botnet.simplehome_xcs7_1002_gafgyt_junk', 'iot_botnet.simplehome_xcs7_1002_gafgyt_scan', 'iot_botnet.simplehome_xcs7_1002_gafgyt_tcp', 'iot_botnet.simplehome_xcs7_1002_gafgyt_udp', 'iot_botnet.simplehome_xcs7_1002_mirai_ack', 'iot_botnet.simplehome_xcs7_1002_mirai_scan', 'iot_botnet.simplehome_xcs7_1002_mirai_syn', 'iot_botnet.simplehome_xcs7_1002_mirai_udp', 'iot_botnet.simplehome_xcs7_1002_mirai_udpplain', 'iot_botnet.simplehome_xcs7_1003_gafgyt_combo', 'iot_botnet.simplehome_xcs7_1003_gafgyt_junk', 'iot_botnet.simplehome_xcs7_1003_gafgyt_scan', 'iot_botnet.simplehome_xcs7_1003_gafgyt_tcp', 'iot_botnet.simplehome_xcs7_1003_gafgyt_udp', 'iot_botnet.simplehome_xcs7_1003_mirai_ack', 'iot_botnet.simplehome_xcs7_1003_mirai_scan', 'iot_botnet.simplehome_xcs7_1003_mirai_syn', 'iot_botnet.simplehome_xcs7_1003_mirai_udp', 'iot_botnet.simplehome_xcs7_1003_mirai_udpplain']

In [64]:
df = pd.read_sql_table("iot_botnet.simplehome_xcs7_1002_mirai_udp", con=engine)
df.head(5)

,MI_dir_L5_weight,MI_dir_L5_mean,MI_dir_L5_variance,MI_dir_L3_weight,MI_dir_L3_mean,MI_dir_L3_variance,MI_dir_L1_weight,MI_dir_L1_mean,MI_dir_L1_variance,MI_dir_L0.1_weight,...,HpHp_L0.1_radius,HpHp_L0.1_covariance,HpHp_L0.1_pcc,HpHp_L0.01_weight,HpHp_L0.01_mean,HpHp_L0.01_std,HpHp_L0.01_magnitude,HpHp_L0.01_radius,HpHp_L0.01_covariance,HpHp_L0.01_pcc
0,1.000000,60.0,0.000000e+00,1.000000,60.0,0.000000e+00,1.000000,60.0,0.000000e+00,1.000000,...,0.0,0.0,0.0,1.0,60.0,0.0,60.0,0.0,0.0,0.0
1,1.999969,60.0,9.094947e-13,1.999982,60.0,4.547474e-13,1.999994,60.0,9.094947e-13,1.999999,...,0.0,0.0,0.0,1.0,60.0,0.0,60.0,0.0,0.0,0.0
2,2.999961,60.0,9.094947e-13,2.999977,60.0,0.000000e+00,2.999992,60.0,0.000000e+00,2.999999,...,0.0,0.0,0.0,1.0,60.0,0.0,60.0,0.0,0.0,0.0
3,3.999857,60.0,0.000000e+00,3.999914,60.0,0.000000e+00,3.999971,60.0,4.547474e-13,3.999997,...,0.0,0.0,0.0,1.0,60.0,0.0,60.0,0.0,0.0,0.0
4,4.999761,60.0,4.547474e-13,4.999857,60.0,0.000000e+00,4.999952,60.0,1.818989e-12,4.999995,...,0.0,0.0,0.0,1.0,60.0,0.0,60.0,0.0,0.0,0.0

In [55]:
folder_path = Path("Z:\Datasets")
file_names = [p.name for p in folder_path.iterdir()]

print(folder_path)
print(file_names)

Z:\Datasets
['credit-card-fraud.arff', 'default of credit card clients.xls', 'detection-of-iot-botnet-attacks', 'glass-identification', 'phishing-email.arff', 'phishing-websites', 'PhishingData.arff', 'PhiUSIIL_Phishing_URL_Dataset.csv', 'taiwan-bankruptcy-prediction.csv', 'UCF-101']

In [56]:
def read_file(file_name):

    if file_name.endswith(".csv"):
        df = pd.read_csv(file_name)

    elif file_name.endswith(".xls"):
        df = pd.read_excel(file_name, header=1)

    else:
        raise ValueError(f"Unsupported file extension for: {basename}")

    return df

In [26]:
file_name = "Z:\Datasets\credit-card-fraud.arff"
data = arff.load(open(file_name, 'r', encoding='utf-8'))
cols = [c[0] for c in data['attributes']]

df = pd.DataFrame(data['data'], columns=cols)
df.head(5)

# df.to_sql(
#     "credit_card_fraud",
#     con=engine,
#     if_exists="replace",
#     index=False,
# )

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,57.877857,0.311140,1.945940,1,1,0,0,0
1,10.829943,0.175592,1.294219,1,0,0,0,0
2,5.091079,0.805153,0.427715,1,0,0,1,0
3,2.247564,5.600044,0.362663,1,1,0,1,0
4,44.190936,0.566486,2.222767,1,1,0,1,0

In [15]:
df = read_file(f"Z:\Datasets\default of credit card clients.xls")
df.head(5)

# df.to_sql(
#     "credit_card_client_default",
#     con=engine,
#     if_exists="replace",
#     index=False,
# )

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

In [37]:
file_name = "Z:\Datasets\PhishingData.arff"
data = arff.load(open(file_name, 'r', encoding='utf-8'))
cols = [c[0] for c in data['attributes']]

df = pd.DataFrame(data['data'], columns=cols)
df.head(5)

# df.to_sql(
#     "phishing_url",
#     con=engine,
#     if_exists="replace",
#     index=False,
# )

353

In [17]:
df = read_file(f"Z:\Datasets\PhiUSIIL_Phishing_URL_Dataset.csv")
df.head(5)

# df.to_sql(
#     "phishing_url_phiusiil",
#     con=engine,
#     if_exists="replace",
#     index=False,
# )

,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,521848.txt,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.0,1.000000,0.522907,...,0,0,1,34,20,28,119,0,124,1
1,31372.txt,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.0,0.666667,0.032650,...,0,0,1,50,9,8,39,0,217,1
2,597387.txt,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.0,0.866667,0.028555,...,0,0,1,10,2,7,42,2,5,1
3,554095.txt,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.0,1.000000,0.522907,...,1,1,1,3,27,15,22,1,31,1
4,151578.txt,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.0,1.000000,0.079963,...,1,0,1,244,15,34,72,1,85,1

In [18]:
df = read_file(r"Z:\Datasets\taiwan-bankruptcy-prediction.csv")
df.head(5)

# df.to_sql(
#     "company_bankruptcy_taiwan",
#     con=engine,
#     if_exists="replace",
#     index=False,
# )

,Bankrupt?,ROA(C) before interest and depreciation before interest,ROA(A) before interest and % after tax,ROA(B) before interest and depreciation after tax,Operating Gross Margin,Realized Sales Gross Margin,Operating Profit Rate,Pre-tax net Interest Rate,After-tax net Interest Rate,Non-industry income and expenditure/revenue,...,Net Income to Total Assets,Total assets to GNP price,No-credit Interval,Gross Profit to Sales,Net Income to Stockholder's Equity,Liability to Equity,Degree of Financial Leverage (DFL),Interest Coverage Ratio (Interest expense to EBIT),Net Income Flag,Equity to Liability
0,1,0.370594,0.424389,0.405750,0.601457,0.601457,0.998969,0.796887,0.808809,0.302646,...,0.716845,0.009219,0.622879,0.601453,0.827890,0.290202,0.026601,0.564050,1,0.016469
1,1,0.464291,0.538214,0.516730,0.610235,0.610235,0.998946,0.797380,0.809301,0.303556,...,0.795297,0.008323,0.623652,0.610237,0.839969,0.283846,0.264577,0.570175,1,0.020794
2,1,0.426071,0.499019,0.472295,0.601450,0.601364,0.998857,0.796403,0.808388,0.302035,...,0.774670,0.040003,0.623841,0.601449,0.836774,0.290189,0.026555,0.563706,1,0.016474
3,1,0.399844,0.451265,0.457733,0.583541,0.583541,0.998700,0.796967,0.808966,0.303350,...,0.739555,0.003252,0.622929,0.583538,0.834697,0.281721,0.026697,0.564663,1,0.023982
4,1,0.465022,0.538432,0.522298,0.598783,0.598783,0.998973,0.797366,0.809304,0.303475,...,0.795016,0.003878,0.623521,0.598782,0.839973,0.278514,0.024752,0.575617,1,0.035490

In [43]:
file_name = "Z:\Datasets\phishing-email.arff"
data = arff.load(open(file_name, 'r', encoding='utf-8'))
cols = [c[0] for c in data['attributes']]

df = pd.DataFrame(data['data'], columns=cols)
df.head(5)

# df.to_sql(
#     "phishing_email",
#     con=engine,
#     if_exists="replace",
#     index=False,
# )

                                       text_combined label
0  hpl nom may 25 2001 see attached file hplno 52...     0
1  nom actual vols 24 th forwarded sabrae zajac h...     0
2  enron actuals march 30 april 1 201 estimated a...     0
3  hpl nom may 30 2001 see attached file hplno 53...     0
4  hpl nom june 1 2001 see attached file hplno 60...     0

In [42]:
file_name = "Z:\Datasets\phishing-websites/Training Dataset.arff"
data = arff.load(open(file_name, 'r', encoding='utf-8'))
cols = [c[0] for c in data['attributes']]

df = pd.DataFrame(data['data'], columns=cols)
df.head(5)

# df.to_sql(
#     "phishing_website",
#     con=engine,
#     if_exists="replace",
#     index=False,
# )

,having_IP_Address,URL_Length,Shortining_Service,having_At_Symbol,double_slash_redirecting,Prefix_Suffix,having_Sub_Domain,SSLfinal_State,Domain_registeration_length,Favicon,...,popUpWidnow,Iframe,age_of_domain,DNSRecord,web_traffic,Page_Rank,Google_Index,Links_pointing_to_page,Statistical_report,Result
0,-1,1,1,1,-1,-1,-1,-1,-1,1,...,1,1,-1,-1,-1,-1,1,1,-1,-1
1,1,1,1,1,1,-1,0,1,-1,1,...,1,1,-1,-1,0,-1,1,1,1,-1
2,1,0,1,1,1,-1,-1,-1,-1,1,...,1,1,1,-1,1,-1,1,0,-1,-1
3,1,0,1,1,1,-1,-1,-1,1,1,...,1,1,-1,-1,1,-1,1,-1,1,-1
4,1,0,-1,1,1,-1,1,1,-1,1,...,-1,1,-1,-1,0,-1,1,1,1,1

In [49]:
file_name = "Z:\Datasets\glass-identification/glass.data"

df = pd.read_csv(file_name, header=None)

cols = ['id_number', 'refractive_index', 'Na_weight_pct', 'Mg_weight_pct',
        'Al_weight_pct', 'Si_weight_pct', 'K_weight_pct', 'Ca_weight_pct',
        'Ba_weight_pct', 'Fe_weight_pct', 'glass_type_code']
df.columns = cols

glass_type_map = {
    1: 'building_windows_float_processed',
    2: 'building_windows_non_float_processed',
    3: 'vehicle_windows_float_processed',
    4: 'vehicle_windows_non_float_processed',
    5: 'containers',
    6: 'tableware',
    7: 'headlamps'
}
df['glass_type'] = df['glass_type_code'].map(glass_type_map)

df.head(5)

# df.to_sql(
#     "glass_identification",
#     con=engine,
#     if_exists="replace",
#     index=False,
# )

,id_number,refractive_index,Na_weight_pct,Mg_weight_pct,Al_weight_pct,Si_weight_pct,K_weight_pct,Ca_weight_pct,Ba_weight_pct,Fe_weight_pct,glass_type_code,glass_type
0,1,1.52101,13.64,4.49,1.10,71.78,0.06,8.75,0.0,0.0,1,building_windows_float_processed
1,2,1.51761,13.89,3.60,1.36,72.73,0.48,7.83,0.0,0.0,1,building_windows_float_processed
2,3,1.51618,13.53,3.55,1.54,72.99,0.39,7.78,0.0,0.0,1,building_windows_float_processed
3,4,1.51766,13.21,3.69,1.29,72.61,0.57,8.22,0.0,0.0,1,building_windows_float_processed
4,5,1.51742,13.27,3.62,1.24,73.08,0.55,8.07,0.0,0.0,1,building_windows_float_processed

In [57]:
iot_folder_path = Path("Z:\Datasets\detection-of-iot-botnet-attacks")
iot_folders = [p.name for p in iot_folder_path.iterdir() if p.is_dir()]

print(iot_folder_path)
print(iot_folders)

Z:\Datasets\detection-of-iot-botnet-attacks
['Danmini_Doorbell', 'Ecobee_Thermostat', 'Ennio_Doorbell', 'Philips_B120N10_Baby_Monitor', 'Provision_PT_737E_Security_Camera', 'Provision_PT_838_Security_Camera', 'Samsung_SNH_1011_N_Webcam', 'SimpleHome_XCS7_1002_WHT_Security_Camera', 'SimpleHome_XCS7_1003_WHT_Security_Camera']

In [59]:
def extract_iot_rar_folders(iot_folder_path):
    iot_folders = [p.name for p in iot_folder_path.iterdir() if p.is_dir()]
    rar_folders = ['gafgyt_attacks.rar', 'mirai_attacks.rar']

    for folder in iot_folders:
        for rar_folder in rar_folders:
            rar_file_path = rf"{iot_folder_path}\{folder}\{rar_folder}"
            dest_file_path = rar_file_path.removesuffix(".rar")
            print(f"**File to be extracted: {rar_file_path}")

            try:
                patoolib.extract_archive(rar_file_path, outdir=dest_file_path)
                print(f"**Extraction complete at location: {dest_file_path}")
            
            except Exception as e:
                print(f"**Error during extration: {e}")
            

## TO DO: Loop through folder to read rest of data and write table to postgresql
def write_iot_tables(iot_folder_path):
    iot_folders = [p.name for p in iot_folder_path.iterdir() if p.is_dir()]
    schema_name = "iot_botnet"

    for folder in iot_folders:

        # benign_df = pd.read_csv(rf"{iot_folder_path}\{folder}\benign_traffic.csv")
        # folder_parts = folder.lower().split("_")
        # folder_table_name = "_".join(folder_parts[:3]) if len(folder_parts) > 3 else folder.lower()
        # table_name = folder_table_name + "_benign_traffic"

        # benign_df.to_sql(
        #     f"{schema_name}.{table_name}",
        #     con=engine,
        #     if_exists='replace',
        #     index=False
        # )
        # print(f"{schema_name}.{table_name} written to PostgreSQL")

        folder_dict = {
            'gafgyt': ['combo', 'junk', 'scan', 'tcp', 'udp'],
            'mirai': ['ack', 'scan', 'syn', 'udp', 'udpplain']
        }

        for k, v in folder_dict.items():
            for f in v:
                file_path = rf"{iot_folder_path}\{folder}\{k}_attacks\{f}.csv"
                # print(file_path)

                try:
                    df = pd.read_csv(file_path)
                    # print(f"{file_path} read")

                    folder_parts = folder.lower().split("_")
                    folder_table_name = "_".join(folder_parts[:3]) if len(folder_parts) > 3 else folder.lower()
                    table_name = f"{folder_table_name}_{k}_{f}"

                    df.to_sql(
                        f"{schema_name}.{table_name}",
                        con=engine,
                        if_exists='replace',
                        index=False
                    )
                    print(f"{schema_name}.{table_name} written to PostgreSQL")

                except Exception as e:
                    print(f"Error reading {file_path}: {e}")

In [43]:
# extract_iot_rar_folders(iot_folder_path)

INFO patool: Extracting Z:\Datasets\detection-of-iot-botnet-attacks\Danmini_Doorbell\gafgyt_attacks.rar ...
INFO patool: ... creating output directory `Z:\Datasets\detection-of-iot-botnet-attacks\Danmini_Doorbell\gafgyt_attacks'.
INFO patool: running "C:\Program Files\7-Zip\7z.EXE" x -aou -oZ:\Datasets\detection-of-iot-botnet-attacks\Danmini_Doorbell\gafgyt_attacks -- Z:\Datasets\detection-of-iot-botnet-attacks\Danmini_Doorbell\gafgyt_attacks.rar

**File to be extracted: Z:\Datasets\detection-of-iot-botnet-attacks\Danmini_Doorbell\gafgyt_attacks.rar

INFO patool: ... Z:\Datasets\detection-of-iot-botnet-attacks\Danmini_Doorbell\gafgyt_attacks.rar extracted to `Z:\Datasets\detection-of-iot-botnet-attacks\Danmini_Doorbell\gafgyt_attacks'.
INFO patool: Extracting Z:\Datasets\detection-of-iot-botnet-attacks\Danmini_Doorbell\mirai_attacks.rar ...
INFO patool: could not find a 'file' executable, falling back to guess mime type by file extension
INFO patool: ... creating output directory `Z:\Datasets\detection-of-iot-botnet-attacks\Danmini_Doorbell\mirai_attacks'.
INFO patool: running "C:\Program Files\7-Zip\7z.EXE" x -aou -oZ:\Datasets\detection-of-iot-botnet-attacks\Danmini_Doorbell\mirai_attacks -- Z:\Datasets\detection-of-iot-botnet-attacks\Danmini_Doorbell\mirai_attacks.rar

**Extraction complete at location: Z:\Datasets\detection-of-iot-botnet-attacks\Danmini_Doorbell\gafgyt_attacks
**File to be extracted: Z:\Datasets\detection-of-iot-botnet-attacks\Danmini_Doorbell\mirai_attacks.rar

INFO patool: ... Z:\Datasets\detection-of-iot-botnet-attacks\Danmini_Doorbell\mirai_attacks.rar extracted to `Z:\Datasets\detection-of-iot-botnet-attacks\Danmini_Doorbell\mirai_attacks'.
INFO patool: Extracting Z:\Datasets\detection-of-iot-botnet-attacks\Ecobee_Thermostat\gafgyt_attacks.rar ...
INFO patool: ... creating output directory `Z:\Datasets\detection-of-iot-botnet-attacks\Ecobee_Thermostat\gafgyt_attacks'.
INFO patool: running "C:\Program Files\7-Zip\7z.EXE" x -aou -oZ:\Datasets\detection-of-iot-botnet-attacks\Ecobee_Thermostat\gafgyt_attacks -- Z:\Datasets\detection-of-iot-botnet-attacks\Ecobee_Thermostat\gafgyt_attacks.rar

**Extraction complete at location: Z:\Datasets\detection-of-iot-botnet-attacks\Danmini_Doorbell\mirai_attacks
**File to be extracted: Z:\Datasets\detection-of-iot-botnet-attacks\Ecobee_Thermostat\gafgyt_attacks.rar

INFO patool: ... Z:\Datasets\detection-of-iot-botnet-attacks\Ecobee_Thermostat\gafgyt_attacks.rar extracted to `Z:\Datasets\detection-of-iot-botnet-attacks\Ecobee_Thermostat\gafgyt_attacks'.
INFO patool: Extracting Z:\Datasets\detection-of-iot-botnet-attacks\Ecobee_Thermostat\mirai_attacks.rar ...
INFO patool: could not find a 'file' executable, falling back to guess mime type by file extension
INFO patool: ... creating output directory `Z:\Datasets\detection-of-iot-botnet-attacks\Ecobee_Thermostat\mirai_attacks'.
INFO patool: running "C:\Program Files\7-Zip\7z.EXE" x -aou -oZ:\Datasets\detection-of-iot-botnet-attacks\Ecobee_Thermostat\mirai_attacks -- Z:\Datasets\detection-of-iot-botnet-attacks\Ecobee_Thermostat\mirai_attacks.rar

**Extraction complete at location: Z:\Datasets\detection-of-iot-botnet-attacks\Ecobee_Thermostat\gafgyt_attacks
**File to be extracted: Z:\Datasets\detection-of-iot-botnet-attacks\Ecobee_Thermostat\mirai_attacks.rar

INFO patool: ... Z:\Datasets\detection-of-iot-botnet-attacks\Ecobee_Thermostat\mirai_attacks.rar extracted to `Z:\Datasets\detection-of-iot-botnet-attacks\Ecobee_Thermostat\mirai_attacks'.
INFO patool: Extracting Z:\Datasets\detection-of-iot-botnet-attacks\Ennio_Doorbell\gafgyt_attacks.rar ...
INFO patool: ... creating output directory `Z:\Datasets\detection-of-iot-botnet-attacks\Ennio_Doorbell\gafgyt_attacks'.
INFO patool: running "C:\Program Files\7-Zip\7z.EXE" x -aou -oZ:\Datasets\detection-of-iot-botnet-attacks\Ennio_Doorbell\gafgyt_attacks -- Z:\Datasets\detection-of-iot-botnet-attacks\Ennio_Doorbell\gafgyt_attacks.rar

**Extraction complete at location: Z:\Datasets\detection-of-iot-botnet-attacks\Ecobee_Thermostat\mirai_attacks
**File to be extracted: Z:\Datasets\detection-of-iot-botnet-attacks\Ennio_Doorbell\gafgyt_attacks.rar

INFO patool: ... Z:\Datasets\detection-of-iot-botnet-attacks\Ennio_Doorbell\gafgyt_attacks.rar extracted to `Z:\Datasets\detection-of-iot-botnet-attacks\Ennio_Doorbell\gafgyt_attacks'.
INFO patool: Extracting Z:\Datasets\detection-of-iot-botnet-attacks\Philips_B120N10_Baby_Monitor\gafgyt_attacks.rar ...
INFO patool: ... creating output directory `Z:\Datasets\detection-of-iot-botnet-attacks\Philips_B120N10_Baby_Monitor\gafgyt_attacks'.
INFO patool: running "C:\Program Files\7-Zip\7z.EXE" x -aou -oZ:\Datasets\detection-of-iot-botnet-attacks\Philips_B120N10_Baby_Monitor\gafgyt_attacks -- Z:\Datasets\detection-of-iot-botnet-attacks\Philips_B120N10_Baby_Monitor\gafgyt_attacks.rar

**Extraction complete at location: Z:\Datasets\detection-of-iot-botnet-attacks\Ennio_Doorbell\gafgyt_attacks
**File to be extracted: Z:\Datasets\detection-of-iot-botnet-attacks\Ennio_Doorbell\mirai_attacks.rar
**Error during extration: file `Z:\Datasets\detection-of-iot-botnet-attacks\Ennio_Doorbell\mirai_attacks.rar' was not found
**File to be extracted: Z:\Datasets\detection-of-iot-botnet-attacks\Philips_B120N10_Baby_Monitor\gafgyt_attacks.rar

INFO patool: ... Z:\Datasets\detection-of-iot-botnet-attacks\Philips_B120N10_Baby_Monitor\gafgyt_attacks.rar extracted to `Z:\Datasets\detection-of-iot-botnet-attacks\Philips_B120N10_Baby_Monitor\gafgyt_attacks'.
INFO patool: Extracting Z:\Datasets\detection-of-iot-botnet-attacks\Philips_B120N10_Baby_Monitor\mirai_attacks.rar ...
INFO patool: could not find a 'file' executable, falling back to guess mime type by file extension
INFO patool: ... creating output directory `Z:\Datasets\detection-of-iot-botnet-attacks\Philips_B120N10_Baby_Monitor\mirai_attacks'.
INFO patool: running "C:\Program Files\7-Zip\7z.EXE" x -aou -oZ:\Datasets\detection-of-iot-botnet-attacks\Philips_B120N10_Baby_Monitor\mirai_attacks -- Z:\Datasets\detection-of-iot-botnet-attacks\Philips_B120N10_Baby_Monitor\mirai_attacks.rar

**Extraction complete at location: Z:\Datasets\detection-of-iot-botnet-attacks\Philips_B120N10_Baby_Monitor\gafgyt_attacks
**File to be extracted: Z:\Datasets\detection-of-iot-botnet-attacks\Philips_B120N10_Baby_Monitor\mirai_attacks.rar

INFO patool: ... Z:\Datasets\detection-of-iot-botnet-attacks\Philips_B120N10_Baby_Monitor\mirai_attacks.rar extracted to `Z:\Datasets\detection-of-iot-botnet-attacks\Philips_B120N10_Baby_Monitor\mirai_attacks'.
INFO patool: Extracting Z:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_737E_Security_Camera\gafgyt_attacks.rar ...
INFO patool: could not find a 'file' executable, falling back to guess mime type by file extension
INFO patool: ... creating output directory `Z:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_737E_Security_Camera\gafgyt_attacks'.

**Extraction complete at location: Z:\Datasets\detection-of-iot-botnet-attacks\Philips_B120N10_Baby_Monitor\mirai_attacks
**File to be extracted: Z:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_737E_Security_Camera\gafgyt_attacks.rar

INFO patool: running "C:\Program Files\7-Zip\7z.EXE" x -aou -oZ:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_737E_Security_Camera\gafgyt_attacks -- Z:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_737E_Security_Camera\gafgyt_attacks.rar
INFO patool: ... Z:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_737E_Security_Camera\gafgyt_attacks.rar extracted to `Z:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_737E_Security_Camera\gafgyt_attacks'.
INFO patool: Extracting Z:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_737E_Security_Camera\mirai_attacks.rar ...
INFO patool: could not find a 'file' executable, falling back to guess mime type by file extension
INFO patool: ... creating output directory `Z:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_737E_Security_Camera\mirai_attacks'.
INFO patool: running "C:\Program Files\7-Zip\7z.EXE" x -aou -oZ:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_737E_Security_Camera\mirai_attacks -- Z:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_737E_Security_Camera\mirai_attacks.rar

**Extraction complete at location: Z:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_737E_Security_Camera\gafgyt_attacks
**File to be extracted: Z:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_737E_Security_Camera\mirai_attacks.rar

INFO patool: ... Z:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_737E_Security_Camera\mirai_attacks.rar extracted to `Z:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_737E_Security_Camera\mirai_attacks'.
INFO patool: Extracting Z:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_838_Security_Camera\gafgyt_attacks.rar ...
INFO patool: could not find a 'file' executable, falling back to guess mime type by file extension
INFO patool: ... creating output directory `Z:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_838_Security_Camera\gafgyt_attacks'.
INFO patool: running "C:\Program Files\7-Zip\7z.EXE" x -aou -oZ:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_838_Security_Camera\gafgyt_attacks -- Z:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_838_Security_Camera\gafgyt_attacks.rar

**Extraction complete at location: Z:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_737E_Security_Camera\mirai_attacks
**File to be extracted: Z:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_838_Security_Camera\gafgyt_attacks.rar

INFO patool: ... Z:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_838_Security_Camera\gafgyt_attacks.rar extracted to `Z:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_838_Security_Camera\gafgyt_attacks'.
INFO patool: Extracting Z:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_838_Security_Camera\mirai_attacks.rar ...
INFO patool: could not find a 'file' executable, falling back to guess mime type by file extension
INFO patool: ... creating output directory `Z:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_838_Security_Camera\mirai_attacks'.
INFO patool: running "C:\Program Files\7-Zip\7z.EXE" x -aou -oZ:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_838_Security_Camera\mirai_attacks -- Z:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_838_Security_Camera\mirai_attacks.rar

**Extraction complete at location: Z:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_838_Security_Camera\gafgyt_attacks
**File to be extracted: Z:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_838_Security_Camera\mirai_attacks.rar

INFO patool: ... Z:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_838_Security_Camera\mirai_attacks.rar extracted to `Z:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_838_Security_Camera\mirai_attacks'.
INFO patool: Extracting Z:\Datasets\detection-of-iot-botnet-attacks\Samsung_SNH_1011_N_Webcam\gafgyt_attacks.rar ...
INFO patool: could not find a 'file' executable, falling back to guess mime type by file extension
INFO patool: ... creating output directory `Z:\Datasets\detection-of-iot-botnet-attacks\Samsung_SNH_1011_N_Webcam\gafgyt_attacks'.
INFO patool: running "C:\Program Files\7-Zip\7z.EXE" x -aou -oZ:\Datasets\detection-of-iot-botnet-attacks\Samsung_SNH_1011_N_Webcam\gafgyt_attacks -- Z:\Datasets\detection-of-iot-botnet-attacks\Samsung_SNH_1011_N_Webcam\gafgyt_attacks.rar

**Extraction complete at location: Z:\Datasets\detection-of-iot-botnet-attacks\Provision_PT_838_Security_Camera\mirai_attacks
**File to be extracted: Z:\Datasets\detection-of-iot-botnet-attacks\Samsung_SNH_1011_N_Webcam\gafgyt_attacks.rar

INFO patool: ... Z:\Datasets\detection-of-iot-botnet-attacks\Samsung_SNH_1011_N_Webcam\gafgyt_attacks.rar extracted to `Z:\Datasets\detection-of-iot-botnet-attacks\Samsung_SNH_1011_N_Webcam\gafgyt_attacks'.
INFO patool: Extracting Z:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1002_WHT_Security_Camera\gafgyt_attacks.rar ...
INFO patool: could not find a 'file' executable, falling back to guess mime type by file extension
INFO patool: ... creating output directory `Z:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1002_WHT_Security_Camera\gafgyt_attacks'.
INFO patool: running "C:\Program Files\7-Zip\7z.EXE" x -aou -oZ:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1002_WHT_Security_Camera\gafgyt_attacks -- Z:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1002_WHT_Security_Camera\gafgyt_attacks.rar

**Extraction complete at location: Z:\Datasets\detection-of-iot-botnet-attacks\Samsung_SNH_1011_N_Webcam\gafgyt_attacks
**File to be extracted: Z:\Datasets\detection-of-iot-botnet-attacks\Samsung_SNH_1011_N_Webcam\mirai_attacks.rar
**Error during extration: file `Z:\Datasets\detection-of-iot-botnet-attacks\Samsung_SNH_1011_N_Webcam\mirai_attacks.rar' was not found
**File to be extracted: Z:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1002_WHT_Security_Camera\gafgyt_attacks.rar

INFO patool: ... Z:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1002_WHT_Security_Camera\gafgyt_attacks.rar extracted to `Z:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1002_WHT_Security_Camera\gafgyt_attacks'.
INFO patool: Extracting Z:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1002_WHT_Security_Camera\mirai_attacks.rar ...
INFO patool: could not find a 'file' executable, falling back to guess mime type by file extension
INFO patool: ... creating output directory `Z:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1002_WHT_Security_Camera\mirai_attacks'.
INFO patool: running "C:\Program Files\7-Zip\7z.EXE" x -aou -oZ:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1002_WHT_Security_Camera\mirai_attacks -- Z:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1002_WHT_Security_Camera\mirai_attacks.rar

**Extraction complete at location: Z:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1002_WHT_Security_Camera\gafgyt_attacks
**File to be extracted: Z:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1002_WHT_Security_Camera\mirai_attacks.rar

INFO patool: ... Z:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1002_WHT_Security_Camera\mirai_attacks.rar extracted to `Z:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1002_WHT_Security_Camera\mirai_attacks'.
INFO patool: Extracting Z:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1003_WHT_Security_Camera\gafgyt_attacks.rar ...
INFO patool: could not find a 'file' executable, falling back to guess mime type by file extension
INFO patool: ... creating output directory `Z:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1003_WHT_Security_Camera\gafgyt_attacks'.

**Extraction complete at location: Z:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1002_WHT_Security_Camera\mirai_attacks
**File to be extracted: Z:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1003_WHT_Security_Camera\gafgyt_attacks.rar

INFO patool: running "C:\Program Files\7-Zip\7z.EXE" x -aou -oZ:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1003_WHT_Security_Camera\gafgyt_attacks -- Z:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1003_WHT_Security_Camera\gafgyt_attacks.rar
INFO patool: ... Z:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1003_WHT_Security_Camera\gafgyt_attacks.rar extracted to `Z:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1003_WHT_Security_Camera\gafgyt_attacks'.
INFO patool: Extracting Z:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1003_WHT_Security_Camera\mirai_attacks.rar ...
INFO patool: could not find a 'file' executable, falling back to guess mime type by file extension
INFO patool: ... creating output directory `Z:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1003_WHT_Security_Camera\mirai_attacks'.
INFO patool: running "C:\Program Files\7-Zip\7z.EXE" x -aou -oZ:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1003_WHT_Security_Camera\mirai_attacks -- Z:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1003_WHT_Security_Camera\mirai_attacks.rar

**Extraction complete at location: Z:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1003_WHT_Security_Camera\gafgyt_attacks
**File to be extracted: Z:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1003_WHT_Security_Camera\mirai_attacks.rar

INFO patool: ... Z:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1003_WHT_Security_Camera\mirai_attacks.rar extracted to `Z:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1003_WHT_Security_Camera\mirai_attacks'.

**Extraction complete at location: Z:\Datasets\detection-of-iot-botnet-attacks\SimpleHome_XCS7_1003_WHT_Security_Camera\mirai_attacks

In [ ]:
write_iot_tables(iot_folder_path)

iot_botnet.danmini_doorbell_gafgyt_combo written to PostgreSQL
iot_botnet.danmini_doorbell_gafgyt_junk written to PostgreSQL
iot_botnet.danmini_doorbell_gafgyt_scan written to PostgreSQL
iot_botnet.danmini_doorbell_gafgyt_tcp written to PostgreSQL
iot_botnet.danmini_doorbell_gafgyt_udp written to PostgreSQL
iot_botnet.danmini_doorbell_mirai_ack written to PostgreSQL
iot_botnet.danmini_doorbell_mirai_scan written to PostgreSQL
iot_botnet.danmini_doorbell_mirai_syn written to PostgreSQL
iot_botnet.danmini_doorbell_mirai_udp written to PostgreSQL
iot_botnet.danmini_doorbell_mirai_udpplain written to PostgreSQL
iot_botnet.ecobee_thermostat_gafgyt_combo written to PostgreSQL
iot_botnet.ecobee_thermostat_gafgyt_junk written to PostgreSQL
iot_botnet.ecobee_thermostat_gafgyt_scan written to PostgreSQL
iot_botnet.ecobee_thermostat_gafgyt_tcp written to PostgreSQL
iot_botnet.ecobee_thermostat_gafgyt_udp written to PostgreSQL
iot_botnet.ecobee_thermostat_mirai_ack written to PostgreSQL
iot_botnet.ecobee_thermostat_mirai_scan written to PostgreSQL
iot_botnet.ecobee_thermostat_mirai_syn written to PostgreSQL
iot_botnet.ecobee_thermostat_mirai_udp written to PostgreSQL
iot_botnet.ecobee_thermostat_mirai_udpplain written to PostgreSQL
iot_botnet.ennio_doorbell_gafgyt_combo written to PostgreSQL
iot_botnet.ennio_doorbell_gafgyt_junk written to PostgreSQL
iot_botnet.ennio_doorbell_gafgyt_scan written to PostgreSQL
iot_botnet.ennio_doorbell_gafgyt_tcp written to PostgreSQL
iot_botnet.ennio_doorbell_gafgyt_udp written to PostgreSQL
Error reading Z:\Datasets\detection-of-iot-botnet-attacks\Ennio_Doorbell\mirai_attacks\ack.csv: [Errno 2] No such file or directory: 'Z:\\Datasets\\detection-of-iot-botnet-attacks\\Ennio_Doorbell\\mirai_attacks\\ack.csv'
Error reading Z:\Datasets\detection-of-iot-botnet-attacks\Ennio_Doorbell\mirai_attacks\scan.csv: [Errno 2] No such file or directory: 'Z:\\Datasets\\detection-of-iot-botnet-attacks\\Ennio_Doorbell\\mirai_attacks\\scan.csv'
Error reading Z:\Datasets\detection-of-iot-botnet-attacks\Ennio_Doorbell\mirai_attacks\syn.csv: [Errno 2] No such file or directory: 'Z:\\Datasets\\detection-of-iot-botnet-attacks\\Ennio_Doorbell\\mirai_attacks\\syn.csv'
Error reading Z:\Datasets\detection-of-iot-botnet-attacks\Ennio_Doorbell\mirai_attacks\udp.csv: [Errno 2] No such file or directory: 'Z:\\Datasets\\detection-of-iot-botnet-attacks\\Ennio_Doorbell\\mirai_attacks\\udp.csv'
Error reading Z:\Datasets\detection-of-iot-botnet-attacks\Ennio_Doorbell\mirai_attacks\udpplain.csv: [Errno 2] No such file or directory: 'Z:\\Datasets\\detection-of-iot-botnet-attacks\\Ennio_Doorbell\\mirai_attacks\\udpplain.csv'
iot_botnet.philips_b120n10_baby_gafgyt_combo written to PostgreSQL
iot_botnet.philips_b120n10_baby_gafgyt_junk written to PostgreSQL
iot_botnet.philips_b120n10_baby_gafgyt_scan written to PostgreSQL
iot_botnet.philips_b120n10_baby_gafgyt_tcp written to PostgreSQL
iot_botnet.philips_b120n10_baby_gafgyt_udp written to PostgreSQL
iot_botnet.philips_b120n10_baby_mirai_ack written to PostgreSQL
iot_botnet.philips_b120n10_baby_mirai_scan written to PostgreSQL
iot_botnet.philips_b120n10_baby_mirai_syn written to PostgreSQL
iot_botnet.philips_b120n10_baby_mirai_udp written to PostgreSQL
iot_botnet.philips_b120n10_baby_mirai_udpplain written to PostgreSQL
iot_botnet.provision_pt_737e_gafgyt_combo written to PostgreSQL
iot_botnet.provision_pt_737e_gafgyt_junk written to PostgreSQL
iot_botnet.provision_pt_737e_gafgyt_scan written to PostgreSQL
iot_botnet.provision_pt_737e_gafgyt_tcp written to PostgreSQL
iot_botnet.provision_pt_737e_gafgyt_udp written to PostgreSQL
iot_botnet.provision_pt_737e_mirai_ack written to PostgreSQL
iot_botnet.provision_pt_737e_mirai_scan written to PostgreSQL
iot_botnet.provision_pt_737e_mirai_syn written to PostgreSQL
iot_botnet.provision_pt_737e_mirai_udp written to PostgreSQL
iot_botnet.provision_pt_737e_mirai_udpplain written to PostgreSQL
iot_botnet.provision_pt_838_gafgyt_combo written to PostgreSQL
iot_botnet.provision_pt_838_gafgyt_junk written to PostgreSQL
iot_botnet.provision_pt_838_gafgyt_scan written to PostgreSQL
iot_botnet.provision_pt_838_gafgyt_tcp written to PostgreSQL
iot_botnet.provision_pt_838_gafgyt_udp written to PostgreSQL
iot_botnet.provision_pt_838_mirai_ack written to PostgreSQL
iot_botnet.provision_pt_838_mirai_scan written to PostgreSQL
iot_botnet.provision_pt_838_mirai_syn written to PostgreSQL
iot_botnet.provision_pt_838_mirai_udp written to PostgreSQL
iot_botnet.provision_pt_838_mirai_udpplain written to PostgreSQL
iot_botnet.samsung_snh_1011_gafgyt_combo written to PostgreSQL
iot_botnet.samsung_snh_1011_gafgyt_junk written to PostgreSQL
iot_botnet.samsung_snh_1011_gafgyt_scan written to PostgreSQL
iot_botnet.samsung_snh_1011_gafgyt_tcp written to PostgreSQL
iot_botnet.samsung_snh_1011_gafgyt_udp written to PostgreSQL
Error reading Z:\Datasets\detection-of-iot-botnet-attacks\Samsung_SNH_1011_N_Webcam\mirai_attacks\ack.csv: [Errno 2] No such file or directory: 'Z:\\Datasets\\detection-of-iot-botnet-attacks\\Samsung_SNH_1011_N_Webcam\\mirai_attacks\\ack.csv'
Error reading Z:\Datasets\detection-of-iot-botnet-attacks\Samsung_SNH_1011_N_Webcam\mirai_attacks\scan.csv: [Errno 2] No such file or directory: 'Z:\\Datasets\\detection-of-iot-botnet-attacks\\Samsung_SNH_1011_N_Webcam\\mirai_attacks\\scan.csv'
Error reading Z:\Datasets\detection-of-iot-botnet-attacks\Samsung_SNH_1011_N_Webcam\mirai_attacks\syn.csv: [Errno 2] No such file or directory: 'Z:\\Datasets\\detection-of-iot-botnet-attacks\\Samsung_SNH_1011_N_Webcam\\mirai_attacks\\syn.csv'
Error reading Z:\Datasets\detection-of-iot-botnet-attacks\Samsung_SNH_1011_N_Webcam\mirai_attacks\udp.csv: [Errno 2] No such file or directory: 'Z:\\Datasets\\detection-of-iot-botnet-attacks\\Samsung_SNH_1011_N_Webcam\\mirai_attacks\\udp.csv'
Error reading Z:\Datasets\detection-of-iot-botnet-attacks\Samsung_SNH_1011_N_Webcam\mirai_attacks\udpplain.csv: [Errno 2] No such file or directory: 'Z:\\Datasets\\detection-of-iot-botnet-attacks\\Samsung_SNH_1011_N_Webcam\\mirai_attacks\\udpplain.csv'
iot_botnet.simplehome_xcs7_1002_gafgyt_combo written to PostgreSQL
iot_botnet.simplehome_xcs7_1002_gafgyt_junk written to PostgreSQL
iot_botnet.simplehome_xcs7_1002_gafgyt_scan written to PostgreSQL
iot_botnet.simplehome_xcs7_1002_gafgyt_tcp written to PostgreSQL
iot_botnet.simplehome_xcs7_1002_gafgyt_udp written to PostgreSQL
iot_botnet.simplehome_xcs7_1002_mirai_ack written to PostgreSQL
iot_botnet.simplehome_xcs7_1002_mirai_scan written to PostgreSQL
iot_botnet.simplehome_xcs7_1002_mirai_syn written to PostgreSQL
iot_botnet.simplehome_xcs7_1002_mirai_udp written to PostgreSQL
iot_botnet.simplehome_xcs7_1002_mirai_udpplain written to PostgreSQL
iot_botnet.simplehome_xcs7_1003_gafgyt_combo written to PostgreSQL
iot_botnet.simplehome_xcs7_1003_gafgyt_junk written to PostgreSQL
iot_botnet.simplehome_xcs7_1003_gafgyt_scan written to PostgreSQL
iot_botnet.simplehome_xcs7_1003_gafgyt_tcp written to PostgreSQL
iot_botnet.simplehome_xcs7_1003_gafgyt_udp written to PostgreSQL
iot_botnet.simplehome_xcs7_1003_mirai_ack written to PostgreSQL
iot_botnet.simplehome_xcs7_1003_mirai_scan written to PostgreSQL
iot_botnet.simplehome_xcs7_1003_mirai_syn written to PostgreSQL
iot_botnet.simplehome_xcs7_1003_mirai_udp written to PostgreSQL
iot_botnet.simplehome_xcs7_1003_mirai_udpplain written to PostgreSQL